# Generated by Django 2.0.4 on 2018-09-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentMarketPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(choices=[(2, 'BTC'), (3, 'ETH'), (4, 'BST')])),
                ('stock_id', models.IntegerField(choices=[(2, 'BTC'), (3, 'ETH'), (4, 'BST')])),
                ('price', models.DecimalField(decimal_places=9, max_digits=18)),
                ('change', models.FloatField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StatsMarketPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(choices=[(2, 'BTC'), (3, 'ETH'), (4, 'BST')])),
                ('stock_id', models.IntegerField(choices=[(2, 'BTC'), (3, 'ETH'), (4, 'BST')])),
                ('price', models.DecimalField(decimal_places=9, max_digits=18)),
                ('granularity', models.IntegerField(choices=[(1, '1h'), (2, '24h'), (3, '7d'), (4, '14d'), (5, 'month'), (6, 'year')])),
                ('updated', models.DateTimeField()),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='statsmarketprice',
            index=models.Index(fields=['unit_id', 'stock_id'], name='pico_framew_unit_id_319dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='currentmarketprice',
            index=models.Index(fields=['unit_id', 'stock_id'], name='pico_framew_unit_id_57b0dc_idx'),
        ),
    ]
