# Generated by Django 2.0.4 on 2018-10-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsMarketPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(choices=[(2, 'BTC'), (3, 'ETH'), (4, 'BST')])),
                ('stock_id', models.IntegerField(choices=[(2, 'BTC'), (3, 'ETH'), (4, 'BST')])),
                ('price', models.DecimalField(decimal_places=18, max_digits=27)),
                ('granularity', models.IntegerField(choices=[(1, '1h'), (2, '24h'), (3, '7d'), (4, '14d'), (5, 'month'), (6, 'year')])),
                ('added', models.DateTimeField()),
            ],
            options={
                'ordering': ('-added',),
            },
        ),
        migrations.AddIndex(
            model_name='statsmarketprice',
            index=models.Index(fields=['unit_id', 'stock_id', 'granularity'], name='pico_framew_unit_id_fd6fe9_idx'),
        ),
    ]
