# Generated by Django 2.1.1 on 2018-09-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentMarketPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(choices=[(4, 'BTC'), (3, 'ETH'), (4, 'BST')])),
                ('stock_id', models.IntegerField(choices=[(4, 'BTC'), (3, 'ETH'), (4, 'BST')])),
                ('price', models.DecimalField(decimal_places=9, max_digits=18)),
                ('change', models.FloatField()),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='currentmarketprice',
            index=models.Index(fields=['unit_id', 'stock_id'], name='pico_framew_unit_id_57b0dc_idx'),
        ),
    ]
