# Generated by Django 2.0.4 on 2018-11-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pico_framework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statsmarketprice',
            name='pico_framew_unit_id_fd6fe9_idx',
        ),
        migrations.AddIndex(
            model_name='statsmarketprice',
            index=models.Index(fields=['unit_id', 'stock_id', 'granularity', 'timestamp'], name='pico_framew_unit_id_5f27db_idx'),
        ),
    ]
