# Generated by Django 2.0.4 on 2019-03-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pico_framework', '0002_auto_20181105_1710'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statsmarketprice',
            name='pico_framew_unit_id_5f27db_idx',
        ),
        migrations.AlterUniqueTogether(
            name='statsmarketprice',
            unique_together={('unit_id', 'stock_id', 'granularity', 'timestamp')},
        ),
    ]
