import collections

MAX_PRICE_DIGITS = 8

USD_ID = -1

BTC_ID = 2
ETH_ID = 3
BST_ID = 4


STOCK_CHOICES = (
    (BTC_ID, "BTC"),
    (ETH_ID, "ETH"),
    (BST_ID, "BST"),
    (USD_ID, "USD")
)

GRANULARITY_HOUR = 1
GRANULARITY_DAY = 2
GRANULARITY_WEEK = 3
GRANULARITY_FORTNIGHTLY = 4
GRANULARITY_MONTH = 5
GRANULARITY_YEAR = 6

GRANULARITY_MINUTE = 100


GRANULARITY_CHOICES = (
    (GRANULARITY_HOUR, '1h'),
    (GRANULARITY_DAY, '24h'),
    (GRANULARITY_WEEK, '7d'),
    (GRANULARITY_FORTNIGHTLY, '14d'),
    (GRANULARITY_MONTH, 'month'),
    (GRANULARITY_YEAR, 'year')
)

GRANULARITY_HOUR_TIME = 1
GRANULARITY_DAY_TIME = 30
GRANULARITY_WEEK_TIME = 200
GRANULARITY_FORTNIGHTLY_TIME = 400
GRANULARITY_MONTH_TIME = 864
GRANULARITY_YEAR_TIME = 43800

GRANULARITY_MINUTE_TIME = 1


GRANULARITY_KINDS = collections.defaultdict(dict)

GRANULARITY_KINDS[GRANULARITY_HOUR] = dict(
    time=GRANULARITY_HOUR_TIME, span=GRANULARITY_HOUR_TIME * 60)

GRANULARITY_KINDS[GRANULARITY_DAY] = dict(
    time=GRANULARITY_DAY_TIME, span=GRANULARITY_DAY_TIME * 48)

GRANULARITY_KINDS[GRANULARITY_WEEK] = dict(
    time=GRANULARITY_WEEK_TIME, span=GRANULARITY_DAY_TIME * 48 * 7)

GRANULARITY_KINDS[GRANULARITY_FORTNIGHTLY] = dict(
    time=GRANULARITY_FORTNIGHTLY_TIME, span=GRANULARITY_FORTNIGHTLY_TIME * 105)

GRANULARITY_KINDS[GRANULARITY_MONTH] = dict(
    time=GRANULARITY_MONTH_TIME, span=GRANULARITY_FORTNIGHTLY_TIME * 110)

GRANULARITY_KINDS[GRANULARITY_YEAR] = dict(
    time=GRANULARITY_YEAR_TIME, span=GRANULARITY_MONTH_TIME * 660)

GRANULARITY_KINDS[GRANULARITY_MINUTE] = dict(
    time=GRANULARITY_MINUTE_TIME, span=GRANULARITY_MINUTE_TIME)
