import collections

BTC_ID = 2
ETH_ID = 3
BST_ID = 4


STOCK_CHOICES = (
    (BTC_ID, "BTC"),
    (ETH_ID, "ETH"),
    (BST_ID, "BST")
)

_GRANULARITY_HOUR = 1
_GRANULARITY_DAY = 2
_GRANULARITY_WEEK = 3
_GRANULARITY_FORTNIGHTLY = 4
_GRANULARITY_MONTH = 5
_GRANULARITY_YEAR = 6

GRANULARITY_CHOICES = (
    (_GRANULARITY_HOUR, '1h'),
    (_GRANULARITY_DAY, '24h'),
    (_GRANULARITY_WEEK, '7d'),
    (_GRANULARITY_FORTNIGHTLY, '14d'),
    (_GRANULARITY_MONTH, 'month'),
    (_GRANULARITY_YEAR, 'year')
)

GRANULARITY_INVERT_MAP = {v: k for k, v in GRANULARITY_CHOICES}


_GRANULARITY_HOUR_TIME = 1
_GRANULARITY_DAY_TIME = 30
_GRANULARITY_WEEK_TIME = 200
_GRANULARITY_FORTNIGHTLY_TIME = 400
_GRANULARITY_MONTH_TIME = 864
_GRANULARITY_YEAR_TIME = 43800


GRANULARITY_KINDS = collections.defaultdict(dict)

GRANULARITY_KINDS[_GRANULARITY_HOUR] = dict(
    time=_GRANULARITY_HOUR_TIME, span=_GRANULARITY_HOUR_TIME * 60)

GRANULARITY_KINDS[_GRANULARITY_DAY] = dict(
    time=_GRANULARITY_DAY_TIME, span=_GRANULARITY_DAY_TIME * 48)

GRANULARITY_KINDS[_GRANULARITY_WEEK] = dict(
    time=_GRANULARITY_WEEK_TIME, span=_GRANULARITY_DAY_TIME * 48 * 7)

GRANULARITY_KINDS[_GRANULARITY_FORTNIGHTLY] = dict(
    time=_GRANULARITY_FORTNIGHTLY_TIME, span=_GRANULARITY_FORTNIGHTLY_TIME *
                                             105)

GRANULARITY_KINDS[_GRANULARITY_MONTH] = dict(
    time=_GRANULARITY_MONTH_TIME, span=_GRANULARITY_FORTNIGHTLY_TIME * 110)

GRANULARITY_KINDS[_GRANULARITY_YEAR] = dict(
    time=_GRANULARITY_YEAR_TIME, span=_GRANULARITY_MONTH_TIME * 660)
